RiiConnect24/Wii-Guide

_pages/en_US/get-started.txt
These tools do not give instructions
=> Minor grammar fix

_pages/en_US/hbc.txt
I found error 404 is priiloder and no prilloader so lok that bether
=> Critial bug fix

_pages/es_MX/CleanRip.txt
=> CleanRip.txt

_pages/es_MX/dump-smb.txt
=> translation for spanish files

_pages/es_MX/dump-wads.txt
spanish version for wii.guide files
=> spanish version for wii.guide files

_pages/es_MX/faq.txt, _pages/es_MX/hbc.txt
=> spanish version

_pages/en_US/faq.txt
Condensed in some places and dumbed down some text.
=> Grammar and clear language

_pages/en_US/hbc.txt
Made it clear on what BootMii does and IOS vs boot2.
=> #BootMiiRights

_pages/en_US/home.txt
I believe, but you may decline this if you want to keep it.
=> Update WiiMC as the YT patcher got cancelled

_pages/es_MX/CleanRip.txt, _pages/es_MX/bootmii.txt, _pages/es_MX/cios.txt, _pages/es_MX/flashhax.txt, _pages/es_MX/hbc.txt, _pages/es_MX/home.txt, _pages/es_MX/letterbomb.txt, _pages/es_MX/priiloader.txt, _pages/es_MX/riiconnect24-batteryfix.txt, _pages/es_MX/riiconnect24-troubleshooting.txt, _pages/es_MX/riiconnect24.txt, _pages/es_MX/site-navigation.txt, _pages/es_MX/str2hax.txt, _pages/es_MX/wiimmfi.txt, _pages/es_MX/wiiwarepatcher.txt
Some strings weren't translated and/or translated incorrectly, also, the images were not displaying correctly on pages, so the "!" symbol before an image link was added.
=> So many fixes on strings

_data/navigation/es_MX.yml, _pages/es_MX/Credits.txt, _pages/es_MX/dump-games.txt, _pages/es_MX/dump-smb.txt, _pages/es_MX/dump-wads.txt, _pages/es_MX/faq.txt, _pages/es_MX/riiconnect24-evc.txt, _pages/es_MX/riiconnect24-troubleshooting.txt, _pages/es_MX/rssmii-remove.txt, _pages/es_MX/rssmii.txt, _pages/es_MX/site-navigation.txt, _pages/es_MX/syscheck.txt, _pages/es_MX/themes.txt, _pages/es_MX/wiimodlite.txt
Just a few corrections and deleted some double-instruction set, also, the incomplete "Sitio Navegacion de" has been changed to "Mapa del sitio" to fit the page_footer correctly
=> Corrections made

_pages/es_MX/riiconnect24.txt, _pages/es_MX/wiimmfi.txt
Same thing, just from another branch
=> A little bit from PR #55

_pages/en_US/riiconnect24.txt
Mention local custom DNS in RiiConnect24 page.
For English locale, translations for other locales appreciated :)
=> Mention local custom DNS in RiiConnect24 page

_pages/en_US/wiimmfi.txt
I edited the wiimmfi patch page to include the str2hax patcher using the EULA (replacing the old FlashHax one), and added some information about the patcher that comes with USB-Loader GX and Wiiflow, and added some information about Wiimms MKW Fun.
=> Update wiimmfi page

_pages/en_US/wiimmfi.txt
Wiimmfi is moving to the new server, this is the new Wiimmfi IP.
=> New Wiimmfi IP

_pages/en_US/priiloader.txt
Fix some wording so people don't extract it to apps and end up with /apps/apps/priiloader/
=> Change some wording

Gemfile, _pages/en_US/riiconnect24-vwii.txt, _pages/en_US/riiconnect24.txt, _pages/en_US/site-navigation.txt
**NOT** to be merged until @KcrPL releases the patcher with vWii support into stable.
=> vWii RiiConnect24 Guide

_pages/it_IT/bootmii.txt, _pages/it_IT/get-started.txt, _pages/it_IT/riiconnect24-vwii.txt, _pages/it_IT/riitag.txt, _pages/it_IT/site-navigation.txt, _pages/it_IT/usbloadergx.txt, _pages/it_IT/wiibackupmanager.txt, _pages/it_IT/wiigsc.txt
I translated all the missing pages in italian.
=> wii.guide Italian Translation

_config.yml, _data/navigation/en_US.yml, _data/navigation/es_MX.yml, _data/navigation/it_IT.yml, _data/navigation/pl_PL.yml, _data/navigation/pt_BR.yml, _pages/en_US/bootmii.md, _pages/en_US/cios.md, _pages/en_US/dump-wads.md
=> Switch Home links from txt to md & Update basic navigation

_pages/en_US/bluebomb.md
- Increased readability for multiple things
- Increased emphasis on `Mini` by capitalising it
- `NTSC` to `USA` to keep consistency with everything else
=> BlueBomb updates

_sass/minimal-mistakes/_base.scss
Before anyone asks, this is tested on dsi.cfw.guide
=> Fix code blocks wrapping

_pages/en_US/wiimmfi.md
Figured it should be included since Wiimmfi patchers are now integrated into the RC24 patcher.
=> Add reference to RiiConnect24 Patcher on Wiimmfi page

_pages/en_US/wiigsc.md
Added instruction to run WiiGSC as an administrator, and that an error will show up if you don't do so, as many users were being confused by this.
=> Add admin requirement

_pages/en_US/site-navigation.md
Markdown fix so the Modding 101 category is properly seperated.
=> Fix category error

_pages/en_US/cleanrip.md, _pages/en_US/dump-games.md, _pages/en_US/dump-smb.md
This removes the dumb index page. Now it uses tabs instead.
JS code by me.
Untested, please test on your own
=> Switch over to a tab system

_pages/en_US/get-started.md
Clarified a few areas that were slightly lacking and also added parts to prevent SD card confusion (happens more than you might think)
=> Clarifications

_pages/en_US/get-started.md
=> SD clarification

_pages/en_US/cleanrip.md
Added info about free space needed for dual layer discs
=> Dual layer free space

_pages/en_US/riitag-wiiu.md
Loads the Wii U Plugin System on startup using a CBHC mod designed for autobooting SDCafiine. Personally tested on my personal Wii U.
=> WUPS on Startup

_pages/en_US/wiilink24.md
Reverts RiiConnect24/Wii-Guide#138
=> Revert "Revert SaveGame Manager GX version"

_pages/en_US/wiilink24.md
Reverts RiiConnect24/Wii-Guide#139
=> Revert "Revert "Revert SaveGame Manager GX version""

_pages/en_US/wiilink24.md
With the latest version of our Public Beta (v2), we remove a workaround that can be best described as jank. The patcher will be shortly updated accordingly.
=> Remove temporary workaround

_pages/en_US/cios-mini.md
Adds WiiFlow Lite as a USB Loader
=> Adds WiiFlow Lite as a USB Loader

_pages/en_US/cios-mini.md, _pages/en_US/news000006.md
You may get error NEWS/FORE000002 after fixing NEWS000006. This shows how to fix it if you get that error.
=> Adds how to fix NEWS/FORE000002

_pages/en_US/usbloadergx.md, _pages/en_US/wiiflow.md
Added how to add games if not using Wii Backup Manager or Witgui. Just clears up confusion for the rarts coming into the server not knowing what to do
=> Added how to add games if not using Wii Backup Manager or Witgui

_pages/en_US/wiibackupmanager.md
I also re-worded a sentence for it to make more sense.
=> Added WiiFlow to Options once complete

_pages/en_US/hbc.md
Just wanted to let you know that the InstallBootMii.jpg doesn't exist
=> A picture no longer exists

_pages/en_US/wiimmfi.md
See https://wiimmfi.de/update, we've released an update for all Wiimmfi patchers.
=> Updated Wiimmfi patcher link

_pages/en_US/wiimmfi.md
Welp, needed to update the patchers again because of a bug, so here are the new links again.
=> Update patcher links again

_pages/en_US/str2hax.md
Added a notice to make sure users know to set DNS back to auto obtain in order to avoid internet connection issues later on.
=> Added final notice about DNS

_pages/en_US/get-started.md
Added notice explaining that guide can still be used on already modded Wiis.
=> Added existing mod notice

_pages/en_US/wiilink.md
Updating WiiLink guide to add SPD/Digicam instructions, and correct Wii no Ma to Wii Room.
=> Add SPD/Digicam Instructions

_pages/en_US/riitag.md
=> RiiTag button is named differently

_pages/en_US/bluebomb.md
Also added more bold for extra "we are not responsible".
=> Forgot a hyphen in the notice--warning

_pages/en_US/bluebomb.md
Basically recommending the use of Live USB over virtual machines as it gets asked quite often in our server and is a very common problem people encounter.
=> Add info about virtualizing bluebomb

_pages/en_US/bootmii.md
Added note as it was unclear whether DPAD left also worked, which it does. Also added note that using eject to skip verification will still eject an inserted disc.
=> Added GC controller note and ejection note

_pages/en_US/riiconnect24-vwii.md
Updated vWii page to use `this guide` instead of the bare link.
=> Update vWii page

_pages/en_US/get-started.md, _pages/en_US/update.md
https://twitter.com/OatmealDome/status/1544731705558319105
=> NUS is up again, so update the `update` guide accordingly

_pages/en_US/cios.md
https://wiibrew.org/wiki/IOS57
https://wiibrew.org/wiki/IOS56
https://wiibrew.org/wiki/IOS38
=> The latest versions of IOS57, 56 and 38 on NUS are bumped up by 1 revision from what d2x wants, thanks 4.3rev03 !!

_pages/en_US/dosanddonts.md
This fixes a typo pointed out by snips#9586 on the RiiConnect24 Discord. Would send a link to the message but I'm on mobile and can't find a copy link button - so find it in #support if you wish lol.
=> Fixed typo in dos and don'ts

_pages/en_US/riiconnect24-dolphin.md, _pages/en_US/riiconnect24-vwii.md
Improvements are made to the RiiConnect24 vWii page.
=> Rewrite parts of the guide

_pages/en_US/update.md
https://discord.com/channels/206934458954153984/1063903202820509737/1063903202820509737
Also what does the <br> do
(it's a line break...)
=> Make the priiloader notice stand out a bit

_pages/en_US/riiconnect24.md, _pages/en_US/wiilink-demae-dominos.md, _pages/en_US/wiilink.md, _pages/en_US/wiimmfi.md
=> Updating WiiLink

_pages/en_US/wiilink.md
Made some slight tweaks to make the main WiiLink guide up-to-date, also adding an info box for those wanting to get Food Delivery Channel (Domino's) after finishing the first section of the guide.
=> Updating main WiiLink guide to be up to date with new .NET CLI patcher

_pages/en_US/cios.md
Too many people mix up whether pack wad should be checked or not
=> Split up "check Pack WAD" from "uncheck Patch IOS" on cios page

_pages/en_US/wiiflow.md
Updated format options for Wiiflow
Explaining best options for formatting
=> updated format options for wiiflow

_pages/en_US/letterbomb.md
and i removed that warning because there's no actual reason for it to be there, time to check commit history or something
=> fix the typo'd {: .notice--info}

_pages/en_US/letterbomb.md
I have no idea why I added the other name MS-DOS when it is not done in any other page mentioning fat32
i love inconsistencies !!
=> "No more than 32GB in size" are you sure about that

_pages/en_US/get-started.md
=> feature wilbrand more in get started page

_pages/en_US/bootmii.md, _pages/en_US/hackmii.md
I made this page blindfolded, i have no idea how it looks on the actual site
=> Create relaunching hackmii installer page

_pages/en_US/site-navigation.md
yeah it's not there even though there's a page
=> Add Nintendont to Site Navigation

_pages/en_US/bootmii.md, _pages/en_US/priiloader.md, _pages/en_US/riiconnect24-vwii.md, _pages/en_US/riiconnect24.md
ft. ~~2~~ 3 other minor changes that i wouldn't to put in a separate pr
=> Update notices on rc24 page

_pages/en_US/cios.md
of course, features some re-ordering
=> remove buttons on cios page

_pages/en_US/usbloadergx.md, _pages/en_US/wiibackupmanager.md
Should add some screenshots to be honest. Like the actual instructions are pretty small anyways
=> Update Wii Backup Manager page

_pages/en_US/priiloader.md
not on Linux right now, cannot preview
=> Add note about autobooting USB loader GX

_pages/en_US/wiimmfi.md
Update dead URL; url no longer works and needs to be updated
=> Update dead URL

_pages/en_US/priiloader.md
linked to releases in github instad of DDL
=> fixed the oops

_pages/en_US/site-navigation.md
=> put riitag-wiiu on site-navigation

_pages/en_US/priiloader.md, _pages/en_US/riiconnect24-vwii.md, _pages/en_US/wiimmfi.md
I have to go to bed so i think i'm just leaving this here
=> That reported brick was because of a power cut

_pages/en_US/bootmiirecover.md
This might be useful, considering that there are no instructions on how to restore from a backup on BootMii. Oh, and please don't delete `images/BootMii/BootMii_Red_Arrow.png`
=> Make a BootMii RestoreMii page

_pages/en_US/wiilink.md
Doing a complete Rewriting of the WiiLink section of this guide, due to it being VERY heavily outdated.
=> Complete Rewriting of wiilink.md

_pages/en_US/home.md
I edited home.md to put periods at the end of other lines that did not have them, but the major edit in this commit is changing the section on Wiiconnect24 services to be less redundant and match the larger writing style of the document. Wiimmfi wasn't explicitly mentioned whereas other services were, so also I changed this to reflect that.
=> Update home.md to remove inconsistencies, be more concise and have clarity
