_pages/en_US/riiconnect24.txt

I'm making the very rash assumption here that you use ordinary Markdown for this file, please edit accordingly if that's not the case.
The []() links had a space for some reason. Also I think it looks more professional on separate lines indented like this.

Clear up error on "What you need" for RiiConnect24

---

_pages/en_US/riiconnect24.txt

Sorry for a second PR in a short time, I just noticed this little thing.
To run the mailparse binary from without the folder on macOS/Linux, you need to open a terminal and run `./mailparse` (The `./` is important because unix). If that doesn't work then you'll have to `chmod +x mailparse` first. 
I dunno how to add much more detail in such a small space so I just put the basic idea. If anyone can improve this then that would be helpful.

Specify ./mailparse

---

_pages/en_US/credits.txt

In the credits page, there is a blank notice box. This removes it. Simple.

Remove blank notice box

---

_pages/en_US/riitag.txt

Wiiflow lite enables it by default, this line is not present in a normal wiiflow lite cfg

Remove uneeded instruction that was confusing people

---

_pages/en_US/dump-games.md

we currently have 3 different pages with the same tutorials

Revert dump-games page to how it was previously

---

_pages/en_US/bootmii.md

Currently, the instructions say to launch the Homebrew Channel and click "Launch BootMii". Alot of people get stuck on this step though because if BootMii is installed as Boot2 as recommended in the previous page, this button doesn't show up. The added info box fixes this by instructing anyone who installed it as Boot2 to simply restart the console to access BootMii.

Add an info box for BootMii Boot2

---

_pages/en_US/themes.md

The warning will now link to a guide on how to safely inject 4.3 themes into the vWii without using methods done by homebrew apps. The guide also has a tutorial to backup the original vWii theme too in case you brick somehow.

Change the invalid notice for vWii theming.

---

_pages/en_US/riitag.md

The RiiTag Wii U tutorial is not available anywhere else on the guide, even in the site navigation.

Add a link to RiiTag on Wii U.

---

_pages/en_US/wiilink24.md

Within Wii no Ma's initial public beta, several regions of Wiis crash or hang prior to creating save data. The latest beta version of SaveGame Manager GX requires a save game already exists for the title before permitting installation. Additionally on some Wiis, regardless of save data existing, the option is not available on the beta.
By using the latest stable version (r127, 2013) which does not include this requirement, these Wiis have a chance of completing installation. Seeing as this workaround will not be required in the future, I feel it is permissible as a temporary workaround.
This additionally includes a few fluency tweaks.

Revert SaveGame Manager GX version

---

_pages/en_US/cios.md

Shows Wiiflow Lite as a Homebrew that now can be used, and will redirect the user to the page

Shows WiiFlow Lite as an option for a USB Loader

---

_pages/en_US/home.md

WiiFlow Lite now redirects to wii.guide page, not gbatemp.

WiiFlow Lite now redirects to wii.guide page

---

_pages/en_US/priiloader.md

In my testing, I have discovered that this alone will not allow playing burned games. Playing burned games would also require either patching the System Menu IOS or changing the System Menu IOS to a cIOS with Priiloader's System Menu IOS option in settings. Probably can be worded better, this is just to get the point across

Clarify IOS249 System Menu Hack

---

_pages/en_US/home.md

Clicking on "bootmii" will redirect you to the guide page, instead of bootmii.org

Changes where "Bootmii" redirects you

---

_pages/en_US/cios.md

Added cIOS 252 (based on IOS38, allows for USB keyboard support in-game), added note to ensure if using an SD card that it is unlocked, as this can be an issue that leads to users not seeing v10 beta52 in the list.

Added extra cIOS and SD card note

---

_pages/en_US/riiconnect24-dolphin.md
_pages/en_US/riiconnect24-vwii.md

The vWii guide and Dolphin guide say Windows Only in front of the RC24 patcher. I took them out as we release the unix patcher yesterday

Added Unix Patcher to parts of the guide that said Windows Only

---

_pages/en_US/faq.md

This is a minor change that adds str2hax and FlashHax exploits to the list of exploits that do not require an SD card, since they don't.

Add str2hax, FlashHax exploits to list of exploits that do not require SD

---

_pages/en_US/wiimmfi.md

In anticipation of yet another Wiimmfi patcher update in the near future, we've configured the Wiimmfi webserver to be able to have version-agnostic links that will always point to the most recent version of the Wiimmfi Patchers, as suggested in #182. 
That should hopefully mean that with more patcher updates the links don't need to be updated every time.

Update Wiimmfi page with links that don't break with every update

---

_pages/en_US/wiimmfi.md

Clarified the CTGP-R wording, making it more consistent with the other two custom track distributions. The previous wording made it seem like there are multiple CTGP-R distributions and the one mentioned is only one of them.

Clarified CTGP-R wording

---

_pages/en_US/bootmii.md
_pages/en_US/priiloader.md

This is a redo of #206; most of the info is the same.
This PR adds 2 notices:
1. BootMii - Re-adds a previous notice about running BootMii if installed only as Boot2
2. Priiloader - Adds a notice about `hacks_hash.ini` in the case that it isn't properly detected by Priiloader due to an sd card being inserted with the file on a usb.
These notices would be helpful to people using the guide, and would solve issues I've seen come up when helping others with homebrew.

Adds relevant notices to the BootMii and Priiloader pages

---

_pages/en_US/riitag.md

With the recent addition of RPC game loading for Citra and Cemu in RiiTag this page should be updated from just Dolphin.

Add Citra and Cemu to the RiiTag page

---

_pages/en_US/bluebomb.md

Honestly we've had like at least 9-10 irreversible bricks due to people installing Wii cios or random Wii IOSes in the past few months and we're all starting to get pretty frustrated so I'm adding this here as an extra big red box people should hopefully see.

Add warning about video guides and their unusually large chance of irriversibly bricking a wii mini

---

_pages/en_US/bluebomb.md
_pages/en_US/dosanddonts.md

Sometimes I just don't understand people. Today someone came in the Wii mini discord and said that bluebomb was failing to jump to entrypoint. I asked whether they put boot.elf in their flash drive and they said "Yes, it was failing as bootmini.elf so I renamed it". Anyway, so there's that now. If you need me for anything I'll be next to my desk banging my head against the wall.

Add wii mini IOS and bootmini warnings

---

_pages/en_US/letterbomb.md

Ever since GeoIP broke for the Letterbomb site, 4.3E has been the region selected by default, and users have been thrown off by this. So I added an extra note explaining this and confirming that the user has chosen the proper region. Also added a note to step 6 about what could happen if the incorrect region is selected.
Believe it or not, some users have had issues with Letterbomb because they thought a USB-SD adapter plugged into the Wii would still work. So added a note about that to step 4.

Notes about region selection and SD adapters

---

_pages/en_US/str2hax.md

New hosting provider, new DNS server.
Old one will be shutdown in a few days.

Update DNS servers to new host for str2hax

---

README.md

Simply fixes the license marker in the readme to not link to the AGPLv3 (since this is MIT licensed), instead linking directly to the [LICENSE.txt](LICENSE.txt) file. Also swaps out the headings to be [MD022](https://github.com/DavidAnson/markdownlint/blob/v0.25.1/doc/Rules.md#md022) and [MD401](https://github.com/DavidAnson/markdownlint/blob/v0.25.1/doc/Rules.md#md041) compliant.

Fix license marker in readme linking to AGPLv3

---

_pages/en_US/riiconnect24-dolphin.md

Since the screenshots in the Unix section are the old ones, which are taken from the Windows command prompt, I thought I'd add a note about that. I plan to replace these, but I either need to fire up WSL or something, or fire up my Ubuntu machine :P

Add note about the unix screenshots in Dolphin

---

_pages/en_US/update.md

This is a change requested on Discord [message](https://discord.com/channels/206934458954153984/288361557044494337/1010342324976492634) ([via](https://discord.gg/rc24)). The reason for this change is including using IOS58 Installer just adds one extra step when you were already downloading stuff from NUS anyway and installing it with Wii Mod Lite, you may as well get IOS58 from there as well, saves a step.

Download IOS58 from NUS via NUS Downloader in the update guide

---

_pages/en_US/str2hax.md

In the current state, the guide doesn't specify that you have to press 'Next' before seeing the pony on the subsequent screen. The users may end up waiting on the screen where they are supposed to press next thinking their DNS configuration or something else went wrong. This should help.

Added a small but necessary instruction in str2hax

---

_pages/en_US/gcbackupmanager.md
_pages/en_US/wiilink-demae-dominos.md

The typos `throughly` and `unneccessary` were found by [typos](https://github.com/crate-ci/typos):
```
error: `throughly` should be `thoroughly`
--> .\wiilink-demae-dominos.md:100:22
|
100 | 7. Review your order throughly before placing the order. When you are ready, click the big green `Order` button.<br><br>
|                      ^^^^^^^^^
|
error: `unneccessary` should be `unnecessary`
--> .\gcbackupmanager.md:37:46
|
37 | Selecting `Install Game (Scrub)` will remove unneccessary data from the game, reducing the game's file size.
|                                              ^^^^^^^^^^^^
|
```

fix: typos  `throughly` and `unneccessary`

---

_pages/en_US/bricks.md

As requested by playerjmr, this page will show all known bricks that can happen to a Wii. Doesn't include Error 003 brick, but a image for it exists at /images/Error003brick.png. Will make a ShowMiiWads page later when I have time.

Create a "bricks" page
